    # The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.14.4 is version 28
    loaderVersion="[31,)"
    # A URL to refer people to when problems occur with this mod
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false

    [[mods]]
      modId="solarenergy"
      version="${version}"
      displayName="Solar Energy"
      logoFile="logo.png"
      credits="PauloFilho, Matheus_Braga, FoxHue445"
      authors="paulojjj"
      description= ""